version: '3.8'

services:
  php_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jedi-api
    restart: unless-stopped
    expose:
      - "80" # 🔹 O Apache escuta na porta 80 nativa
    volumes:
      - ./:/var/www/html 
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DIR_PROJETO=${DIR_PROJETO}

      # Recuperação de senha
      - FRONTEND_URL=${FRONTEND_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=20000
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    hostname: jedi-api
    networks:
      - jedieduca-network

networks:
  jedieduca-network:
    external: true